[workspace]
resolver = "2"
members = [
    "crates/usb",
    "crates/rndis",
    "crates/netstack",
    "crates/tun",
    "crates/muta",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/jost-s/macos-usb-tether-android"

[workspace.dependencies]
muta-usb = { path = "crates/usb" }
muta-rndis = { path = "crates/rndis" }
muta-netstack = { path = "crates/netstack" }
muta-tun = { path = "crates/tun" }

anyhow = "1"
thiserror = "2"
futures-lite = "2"
libc = "0.2"
log = "0.4"
env_logger = "0.11"
nusb = "0.2"
rusb = "0.9"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
