[package]
name = "muta-usb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
futures-lite.workspace = true
log.workspace = true
nusb.workspace = true
thiserror.workspace = true
rusb = { workspace = true, optional = true }

[dev-dependencies]
env_logger.workspace = true

[features]
default = []
libusb = ["dep:rusb"]

[[example]]
name = "probe"
