[package]
name = "muta"
description = "Android USB tethering for macOS, in userspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "muta"
path = "src/main.rs"

[dependencies]
muta-usb.workspace = true
muta-rndis.workspace = true
muta-netstack.workspace = true
muta-tun.workspace = true

anyhow.workspace = true
libc.workspace = true
env_logger.workspace = true
log.workspace = true

[features]
libusb = ["muta-usb/libusb"]
